# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=5
      - GRID_BROWSER_TIMEOUT=180000
      - GRID_TIMEOUT=180000
      - JAVA_OPTS=-Xms2g -Xmx6g
    depends_on:
      - insta-actor-user1
      - insta-actor-user2
  chrome:
    image: selenium/node-chrome:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

  insta-actor-user1:
    image: instaactor:v0.1
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - JAVA_OPTS=-Xmx4g
    command: >
      exec:java -Dexec.mainClass=com.dudar.runner.Runner -Dexec.args="/usr/src/app/data/user1.properties /usr/src/app/data/tags1.csv"

  insta-actor-user2:
    image: instaactor:v0.1
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    command: >
      exec:java -Dexec.mainClass=com.dudar.runner.Runner -Dexec.args="/usr/src/app/data/user2.properties /usr/src/app/data/tags2.csv"